# fly.toml app configuration file generated for hello-static-bold-cloud-6585 on 2024-12-05T15:17:05-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hello-static-bold-cloud-6585'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
